const defaultRules = [
  {
    role: 'visitor',
    resource: 'middleware.loader',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'middleware.loader',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'middleware.loader',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'middleware.googleAuth',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'middleware.googleAuth',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'middleware.googleAuth',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'middleware.img',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'middleware.img',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'middleware.img',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'middleware.data',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'middleware.data',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'middleware.data',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'middleware.list',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'middleware.list',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'slide',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'slide',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'slide',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'slide',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'slide',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'slide',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'slide',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'slide',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'slide',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'request',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'request',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'request',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'request',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'request',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'request',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'request',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'mark',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'mark.types',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark.types',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark.types',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'mark.multi',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark.multi',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark.multi',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'mark.spatial',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark.spatial',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark.spatial',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'mark.findMarkTypes',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark.findMarkTypes',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark.findMarkTypes',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'mark',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'mark',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'presetLabel',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'presetLabel',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'presetLabel',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'presetLabel',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'presetLabel',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'presetLabel',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'presetLabel',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'presetLabel',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'presetLabel',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'template',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'template',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'template',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'template',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'template',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'template',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'template',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'template',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'template',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'heatmap',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmap',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmap',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'heatmap.types',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmap.types',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmap.types',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmap',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmap',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmap',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmap',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmap',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmap',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'heatmapEdit',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmapEdit',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmapEdit',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmapEdit',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmapEdit',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmapEdit',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmapEdit',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'heatmapEdit',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'heatmapEdit',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'log',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'log',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'log',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'log',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'log',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'log',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'log',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'log',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'log',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'log',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'freeform',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'freeform',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'freeform',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'freeform',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'freeform',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'freeform',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'freeform',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'freeform',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'freeform',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'freeform',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'configuration',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'configuration',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'configuration',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'configuration',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'configuration',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'configuration',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'configuration',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'configuration',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'configuration',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'user',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'user',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'user',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'visitor',
    resource: 'user.wcido',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'user.wcido',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'user.wcido',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'user',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'user',
    action: 'create:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'user',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'user',
    action: 'delete:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'user',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'user',
    action: 'update:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'workbench.uploadDataset',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'workbench.uploadDataset',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'workbench.trainModel',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'workbench.trainModel',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'workbench.deleteUserData',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'workbench.deleteUserData',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'editor',
    resource: 'workbench.modelDownload',
    action: 'read:any',
    attributes: ['*'],
  },
  {
    role: 'admin',
    resource: 'workbench.modelDownload',
    action: 'read:any',
    attributes: ['*'],
  },
];

module.exports = defaultRules;
